<?php

// Ford Vehicles

function vin_ford_lookups($_1) {

/* sample:

'W02': 'Ford F-Series, F-150, Crew Cab, Flareside, 2WD'
'W04': 'Ford F-Series, F-150, Crew Cab, Flareside, 4WD'
'W12': 'Ford F-Series, F-150, Crew Cab, 2WD'
'W14': 'Ford F-Series, F-150, Crew Cab, 4WD'
'W20': 'Ford F-Series, F-250, Crew Cab, 2WD'
'W21': 'Ford F-Series, F-250, Crew Cab, 4WD'
'W30': 'Ford F-Series, F-350, Crew Cab, 2WD, Single Rear Wheels'
'W31': 'Ford F-Series, F-350, Crew Cab, 4WD, Single Rear Wheels'
'W32': 'Ford F-Series, F-350, Crew Cab, 2WD, Dual Rear Wheels'
'W33': 'Ford F-Series, F-350, Crew Cab, 4WD, Dual Rear Wheels'
'W36': 'Ford F-Series, F-350, Crew Cab, 2WD, CA XL, Dual Rear Wheels'
'W37': 'Ford F-Series, F-350, Crew Cab, 4WD, CA XL, Dual Rear Wheels'
'W46': 'Ford F-Series, F-450, Crew Cab, 2WD'
'W47': 'Ford F-Series, F-450, Crew Cab, 4WD'
'W56': 'Ford F-Series, F-550, Crew Cab, 2WD'
'W57': 'Ford F-Series, F-550, Crew Cab, 4WD'
'W65': 'Ford F-Series, F-650, Crew Cab, Straight Frame'
'W66': 'Ford F-Series, F-650, Crew Cab, Pro Loader'
'W75': 'Ford F-Series, F-750, Crew Cab, Straight Frame'
'W76': 'Ford F-Series, F-750, Crew Cab, Severe Service'
*/
}